"""
Django settings for documents project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (os.getenv('DEBUG', 'False') or '').strip().lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = ['localhost', '127.0.0.1','ida-chungtu.f88.co','chungtu.f88.vn']

CSRF_TRUSTED_ORIGINS = [
    'https://ida-chungtu.f88.co','https://chungtu.f88.vn',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "app_documents.apps.AppDocumentsConfig",
    "app_admindocuments.apps.AdmindocumentsConfig",
    "app_workshift.apps.AppWorkshiftConfig",
    "gapo_relay.apps.GapoRelayConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'documents.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join( BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app_documents.context_processors.current_time'
            ],
        },
    },
]

WSGI_APPLICATION = 'documents.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
# This part of the code is configuring the default database settings for a Django project.
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'postgres',
    #     'USER': 'postgres',
    #     'PASSWORD': 'Pvh12345678@F88vn',
    #     'HOST': 'localhost',
    #     'PORT': '5432',
    #     }
    }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#         }
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

AUTH_PASSWORD_VALIDATORS = [
    # ... other validators ...
    {
        'NAME': 'app_documents.validators.CustomPasswordValidator',
        'OPTIONS': {
            'min_length': 8,  # You can set the minimum length here
        }
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'  # This should start with a forward slash '/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (Images, Videos, Audios)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


LOGIN_REDIRECT_URL = 'home'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = os.environ.get('EMAIL_PORT')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')

# GAPO bot settings
GAPO_API_URL = os.getenv('GAPO_API_URL')
GAPO_BOT_API_KEY = (os.getenv('BOT_API_KEY') or '').strip()
GAPO_BOT_ID = os.getenv('BOT_ID')
GAPO_WEBHOOK_SECRET = (os.getenv('GAPO_WEBHOOK_SECRET') or '').strip()
PUBLIC_APP_BASE_URL = (os.getenv('PUBLIC_APP_BASE_URL') or '').strip().rstrip('/')
GAPO_CONNECT_TIMEOUT = float(os.getenv('GAPO_CONNECT_TIMEOUT', '3.05'))
GAPO_READ_TIMEOUT = float(os.getenv('GAPO_READ_TIMEOUT', '5'))

# GAPO public webhook store-and-pull relay. Both secrets fail closed when unset.
GAPO_RELAY_INGRESS_SECRET = (os.getenv('GAPO_RELAY_INGRESS_SECRET') or '').strip()
GAPO_RELAY_DELIVERY_TOKEN = (os.getenv('GAPO_RELAY_DELIVERY_TOKEN') or '').strip()
GAPO_RELAY_MAX_BODY_BYTES = int(os.getenv('GAPO_RELAY_MAX_BODY_BYTES', str(10 * 1024 * 1024)))
GAPO_RELAY_DELIVERY_MAX_BODY_BYTES = int(os.getenv('GAPO_RELAY_DELIVERY_MAX_BODY_BYTES', '65536'))
GAPO_RELAY_DEFAULT_LEASE_SECONDS = int(os.getenv('GAPO_RELAY_DEFAULT_LEASE_SECONDS', '120'))
GAPO_RELAY_MAX_LEASE_SECONDS = int(os.getenv('GAPO_RELAY_MAX_LEASE_SECONDS', '3600'))
GAPO_RELAY_MAX_BATCH_SIZE = int(os.getenv('GAPO_RELAY_MAX_BATCH_SIZE', '100'))
GAPO_RELAY_MAX_ATTEMPTS = int(os.getenv('GAPO_RELAY_MAX_ATTEMPTS', '20'))
GAPO_RELAY_MAX_BACKOFF_SECONDS = int(os.getenv('GAPO_RELAY_MAX_BACKOFF_SECONDS', '900'))
GAPO_RELAY_SECRET_GRACE_SECONDS = int(os.getenv('GAPO_RELAY_SECRET_GRACE_SECONDS', '86400'))
GAPO_RELAY_RETENTION_DAYS = int(os.getenv('RELAY_RETENTION_DAYS', '30'))
GAPO_RELAY_DEAD_LETTER_RETENTION_DAYS = int(os.getenv('RELAY_DEAD_LETTER_DAYS', '90'))

# Django otherwise rejects request.body at its lower global default before the
# relay can enforce GAPO_RELAY_MAX_BODY_BYTES and return a JSON 413 response.
DATA_UPLOAD_MAX_MEMORY_SIZE = max(
    int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', str(2_621_440))),
    GAPO_RELAY_MAX_BODY_BYTES,
)

# Relay operational logs go to stdout for Docker/Gunicorn collection. Log
# records intentionally exclude webhook paths, secrets and raw payloads.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'relay': {
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'relay_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'relay',
        },
    },
    'loggers': {
        'gapo_relay': {
            'handlers': ['relay_console'],
            'level': os.getenv('GAPO_RELAY_LOG_LEVEL', 'INFO').upper(),
            'propagate': False,
        },
    },
}

# Borrow request API key
BORROW_REQUEST_API_KEY = (os.getenv('BORROW_REQUEST_API_KEY') or '').strip()

# GDDB intake API token for Prefect/manual external integrations.
GDDB_INTAKE_TOKEN = (os.getenv('GDDB_INTAKE_TOKEN') or '').strip()
# A GDDB case is released when no claim heartbeat is received for this period.
GDDB_CASE_CLAIM_MINUTES = int(os.getenv('GDDB_CASE_CLAIM_MINUTES', '240'))

USER_PRESENCE_ACTIVE_GAP = int(os.getenv('USER_PRESENCE_ACTIVE_GAP', '120'))
USER_PRESENCE_ONLINE_WINDOW = int(os.getenv('USER_PRESENCE_ONLINE_WINDOW', '300'))
USER_PRESENCE_HEARTBEAT_SECONDS = int(os.getenv('USER_PRESENCE_HEARTBEAT_SECONDS', '60'))

AUTH_PASSWORD_RESET_SUBJECT = 'registration/password_reset_subject.txt'
PASSWORD_RESET_EMAIL_TEMPLATE = 'registration/password_reset_email.html'

# Celery settings (dùng chung một URL)
CELERY_URL = os.getenv('CELERY_URL') or os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_BROKER_URL = CELERY_URL
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
