# Generated by Django 5.0.4 on 2026-09-15 15:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_documents', '0039_package_history_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('report_month', models.DateField(help_text='Ngày đầu tiên của tháng chiến dịch', unique=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('data_review', 'Chờ kiểm tra dữ liệu'), ('ready', 'Sẵn sàng phát hành'), ('active', 'Đang phản hồi'), ('closed', 'Đã chốt'), ('cancelled', 'Đã hủy')], db_index=True, default='draft', max_length=20)),
                ('response_opens_at', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateTimeField(blank=True, null=True)),
                ('link_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaigns_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dec_campaign',
                'ordering': ['-report_month'],
            },
        ),
        migrations.CreateModel(
            name='CampaignError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_key', models.CharField(max_length=255)),
                ('error_type', models.CharField(choices=[('folder', 'Lỗi thiếu quyển chứng từ'), ('document', 'Lỗi chứng từ không hợp lệ')], max_length=20)),
                ('source_object_id', models.BigIntegerField(blank=True, null=True)),
                ('code', models.TextField(blank=True)),
                ('manager_snapshot', models.JSONField(blank=True, default=dict)),
                ('contract_code', models.CharField(blank=True, max_length=50)),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('employee_code', models.CharField(blank=True, max_length=100)),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('business_type_name', models.CharField(blank=True, max_length=500)),
                ('document_type_name', models.TextField(blank=True)),
                ('checking_issue', models.TextField()),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ready', 'Sẵn sàng phát hành'), ('waiting_shop', 'Chờ PGD phản hồi'), ('shop_draft', 'PGD đang cập nhật'), ('shop_submitted', 'Chờ team kiểm tra'), ('shop_supplement', 'Yêu cầu PGD bổ sung'), ('waiting_area', 'Chờ Area xác nhận'), ('area_returned', 'Area yêu cầu xử lý lại'), ('area_confirmed', 'Area đã xác nhận'), ('closed', 'Đã chốt'), ('excluded', 'Loại khỏi chiến dịch'), ('cancelled', 'Đã hủy')], default='ready', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_errors', to='app_documents.areamanager')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='app_document_campaigns.campaign')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_errors', to='app_documents.documentsdetail')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_errors', to='app_documents.folder')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_errors', to='app_documents.region')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_errors', to='app_documents.shop')),
            ],
            options={
                'db_table': 'dec_campaign_error',
            },
        ),
        migrations.CreateModel(
            name='CampaignSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Định kỳ'), ('published', 'Phát hành'), ('deadline', 'Hết hạn phản hồi'), ('team_approved', 'Team hoàn tất'), ('area_confirmed', 'Area hoàn tất'), ('closed', 'Chốt chiến dịch')], max_length=30)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='app_document_campaigns.campaign')),
            ],
            options={
                'db_table': 'dec_campaign_snapshot',
            },
        ),
        migrations.CreateModel(
            name='CampaignSnapshotMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('global', 'Toàn chiến dịch'), ('region', 'Region'), ('area', 'Area'), ('shop', 'PGD')], max_length=10)),
                ('scope_key', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('total', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='app_document_campaigns.campaignsnapshot')),
            ],
            options={
                'db_table': 'dec_campaign_snapshot_metric',
            },
        ),
        migrations.CreateModel(
            name='CampaignStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app_document_campaigns.campaign')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_status_changes', to=settings.AUTH_USER_MODEL)),
                ('error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='app_document_campaigns.campaignerror')),
            ],
            options={
                'db_table': 'dec_campaign_status_history',
            },
        ),
        migrations.CreateModel(
            name='CampaignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('sql', 'SQL'), ('excel', 'Excel'), ('adjustment', 'Điều chỉnh')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('validated', 'Đã kiểm tra'), ('published', 'Đã phát hành'), ('superseded', 'Đã thay thế')], default='draft', max_length=20)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app_document_campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dec_campaign_version',
                'ordering': ['campaign_id', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='campaignerror',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='errors', to='app_document_campaigns.campaignversion'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_campaigns', to='app_document_campaigns.campaignversion'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_checklists_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dec_checklist_template',
            },
        ),
        migrations.CreateModel(
            name='ChecklistQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('single', 'Một lựa chọn'), ('multiple', 'Nhiều lựa chọn'), ('text', 'Nội dung tự do')], max_length=20)),
                ('error_type', models.CharField(blank=True, help_text='Để trống nếu áp dụng cho mọi loại lỗi', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_document_campaigns.checklisttemplate')),
            ],
            options={
                'db_table': 'dec_checklist_question',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='campaignerror',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_errors', to='app_document_campaigns.checklisttemplate'),
        ),
        migrations.CreateModel(
            name='ShopAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('allowed_email', models.EmailField(max_length=254)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('response_deadline', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_links', to='app_document_campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_links_created', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_links', to='app_documents.shop')),
            ],
            options={
                'db_table': 'dec_shop_access_link',
            },
        ),
        migrations.CreateModel(
            name='ShopResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_code', models.CharField(blank=True, max_length=100)),
                ('answer_payload', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã gửi'), ('reopened', 'Đã mở bổ sung')], default='draft', max_length=20)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_response', to='app_document_campaigns.campaignerror')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_responses', to='app_documents.shop')),
            ],
            options={
                'db_table': 'dec_shop_response',
            },
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='app_document_campaigns.checklistquestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='app_document_campaigns.shopresponse')),
            ],
            options={
                'db_table': 'dec_checklist_answer',
            },
        ),
        migrations.CreateModel(
            name='ShopSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_submissions', to='app_document_campaigns.campaign')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_submissions', to='app_documents.shop')),
            ],
            options={
                'db_table': 'dec_shop_submission',
            },
        ),
        migrations.CreateModel(
            name='TeamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Phê duyệt'), ('supplement', 'Yêu cầu bổ sung'), ('excluded', 'Loại khỏi chiến dịch')], max_length=20)),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reviews', to='app_document_campaigns.campaignerror')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dec_team_review',
            },
        ),
        migrations.CreateModel(
            name='AreaConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('confirmed', 'Xác nhận'), ('returned', 'Trả lại team')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_area_actions', to=settings.AUTH_USER_MODEL)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_confirmations', to='app_document_campaigns.campaignerror')),
            ],
            options={
                'db_table': 'dec_area_confirmation',
                'indexes': [models.Index(fields=['error', '-created_at'], name='dec_area_error_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaignsnapshot',
            index=models.Index(fields=['campaign', '-captured_at'], name='dec_snap_campaign_time_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignsnapshotmetric',
            index=models.Index(fields=['snapshot', 'scope_type', 'scope_key'], name='dec_metric_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignsnapshotmetric',
            constraint=models.UniqueConstraint(fields=('snapshot', 'scope_type', 'scope_key', 'status'), name='dec_uq_snapshot_metric'),
        ),
        migrations.AddIndex(
            model_name='campaignstatushistory',
            index=models.Index(fields=['campaign', '-changed_at'], name='dec_hist_campaign_time_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignstatushistory',
            index=models.Index(fields=['error', '-changed_at'], name='dec_hist_error_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignversion',
            constraint=models.UniqueConstraint(fields=('campaign', 'version_number'), name='dec_uq_campaign_version'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('code', 'version_number'), name='dec_uq_checklist_version'),
        ),
        migrations.AddConstraint(
            model_name='checklistquestion',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='dec_uq_question_code'),
        ),
        migrations.AddIndex(
            model_name='campaignerror',
            index=models.Index(fields=['campaign', 'shop', 'status'], name='dec_err_campaign_shop_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignerror',
            index=models.Index(fields=['campaign', 'area_manager', 'status'], name='dec_err_campaign_area_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignerror',
            index=models.Index(fields=['campaign', 'region', 'status'], name='dec_err_campaign_region_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignerror',
            index=models.Index(fields=['campaign', 'error_type'], name='dec_err_campaign_type_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignerror',
            index=models.Index(fields=['campaign', 'version'], name='dec_err_campaign_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignerror',
            constraint=models.UniqueConstraint(fields=('campaign', 'source_key'), name='dec_uq_campaign_source'),
        ),
        migrations.AddConstraint(
            model_name='campaignerror',
            constraint=models.CheckConstraint(check=models.Q(('folder__isnull', False), ('document__isnull', False), ('source_object_id__isnull', False), _connector='OR'), name='dec_ck_error_source'),
        ),
        migrations.AddConstraint(
            model_name='shopaccesslink',
            constraint=models.UniqueConstraint(fields=('campaign', 'shop'), name='dec_uq_campaign_shop_link'),
        ),
        migrations.AddIndex(
            model_name='shopresponse',
            index=models.Index(fields=['shop', '-updated_at'], name='dec_resp_shop_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='shopresponse',
            index=models.Index(fields=['status', 'updated_at'], name='dec_resp_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklistanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='dec_uq_response_question'),
        ),
        migrations.AddConstraint(
            model_name='shopsubmission',
            constraint=models.UniqueConstraint(fields=('campaign', 'shop'), name='dec_uq_campaign_shop_submit'),
        ),
        migrations.AddIndex(
            model_name='teamreview',
            index=models.Index(fields=['error', '-created_at'], name='dec_review_error_time_idx'),
        ),
    ]
