# Generated by Django 5.0.4 on 2026-09-16 11:29

import django.db.models.deletion
from django.db import migrations, models


def seed_hardcopy_shop_checklist(apps, schema_editor):
    Campaign = apps.get_model("app_document_campaigns", "Campaign")
    CampaignError = apps.get_model("app_document_campaigns", "CampaignError")
    CampaignType = apps.get_model("app_document_campaigns", "CampaignType")
    ChecklistQuestion = apps.get_model("app_document_campaigns", "ChecklistQuestion")
    ChecklistTemplate = apps.get_model("app_document_campaigns", "ChecklistTemplate")

    creator_id = (
        Campaign.objects.order_by("created_at").values_list("created_by_id", flat=True).first()
    )
    campaign_type = CampaignType.objects.filter(code="hardcopy-document-error").first()
    if not creator_id or not campaign_type:
        return

    template, _ = ChecklistTemplate.objects.get_or_create(
        code="SHOP_HARDCOPY_RESPONSE",
        version_number=1,
        defaults={
            "name": "Phản hồi book lỗi chứng từ bản cứng",
            "is_active": True,
            "created_by_id": creator_id,
        },
    )
    ChecklistQuestion.objects.get_or_create(
        template=template,
        code="SHOP_RESPONSE",
        defaults={
            "label": "PGD phản hồi",
            "question_type": "single",
            "options": ["PGD xác nhận lỗi", "PGD hẹn bổ sung chứng từ"],
            "is_required": True,
            "sort_order": 10,
            "is_active": True,
        },
    )
    CampaignType.objects.filter(pk=campaign_type.pk).update(shop_checklist_template=template)
    CampaignError.objects.filter(
        campaign__campaign_type_id=campaign_type.pk,
        checklist_template__isnull=True,
    ).update(checklist_template=template)


def unassign_hardcopy_shop_checklist(apps, schema_editor):
    CampaignType = apps.get_model("app_document_campaigns", "CampaignType")
    CampaignType.objects.filter(code="hardcopy-document-error").update(
        shop_checklist_template=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0007_campaign_type_code_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntype',
            name='shop_checklist_template',
            field=models.ForeignKey(blank=True, help_text='Cấu hình dropdown/câu hỏi dành cho PGD phản hồi.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_types', to='app_document_campaigns.checklisttemplate'),
        ),
        migrations.RunPython(seed_hardcopy_shop_checklist, unassign_hardcopy_shop_checklist),
    ]
