# Generated by Django 5.0.4 on 2026-09-18 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0010_campaign_response_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamReviewExcelJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('export', 'Xuất Excel'), ('import', 'Import Excel')], max_length=10)),
                ('status', models.CharField(default='queued', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('input_file', models.FileField(blank=True, upload_to='document_campaigns/team_review/imports/%Y/%m/')),
                ('output_file', models.FileField(blank=True, upload_to='document_campaigns/team_review/exports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_excel_jobs', to='app_document_campaigns.campaign')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='teamreviewexceljob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('campaign', 'kind'), name='dec_one_active_review_excel'),
        ),
    ]
