# Generated by Django 5.0.4 on 2026-09-29 14:14

from django.db import migrations, models


OLD_DEFAULT = (
    "Kính gửi {{shop_name}},\n\n"
    "Phòng giao dịch vui lòng kiểm tra và phản hồi chiến dịch {{campaign_name}}.\n"
    "Hạn phản hồi: {{response_deadline}}\n"
    "Link hết hạn: {{link_expires_at}}\n\n"
    "Link phản hồi: {{response_url}}\n\n"
    "Trân trọng."
)
NEW_DEFAULT = OLD_DEFAULT.replace("Kính gửi {{shop_name}}", "Kính gửi PGD {{shop_name}}", 1)


def update_default_pgd_greeting(apps, schema_editor):
    config = apps.get_model("app_document_campaigns", "CampaignEmailConfig")
    config.objects.filter(body_template=OLD_DEFAULT).update(body_template=NEW_DEFAULT)


def restore_default_pgd_greeting(apps, schema_editor):
    config = apps.get_model("app_document_campaigns", "CampaignEmailConfig")
    config.objects.filter(body_template=NEW_DEFAULT).update(body_template=OLD_DEFAULT)


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0016_campaign_email_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignemailconfig',
            name='reply_to_email',
        ),
        migrations.RunPython(update_default_pgd_greeting, restore_default_pgd_greeting),
        migrations.AlterField(
            model_name='campaignemailconfig',
            name='body_template',
            field=models.TextField(default='Kính gửi PGD {{shop_name}},\n\nPhòng giao dịch vui lòng kiểm tra và phản hồi chiến dịch {{campaign_name}}.\nHạn phản hồi: {{response_deadline}}\nLink hết hạn: {{link_expires_at}}\n\nLink phản hồi: {{response_url}}\n\nTrân trọng.'),
        ),
    ]
