# Generated by Django 5.0.4 on 2026-09-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0017_simplify_pgd_email_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccesslink',
            name='first_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
