# Generated by Django 5.0.4 on 2026-09-29 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0018_track_first_shop_link_open'),
        ('app_documents', '0043_package_history_action_db_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='areaconfirmation',
            name='access_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='app_document_campaigns.areamanageraccesslink'),
        ),
        migrations.AddField(
            model_name='areaconfirmation',
            name='area_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_confirmations', to='app_documents.areamanager'),
        ),
        migrations.AlterField(
            model_name='areaconfirmation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_campaign_area_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
