# Generated by Django 5.0.4 on 2026-10-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0033_campaignemailbatch_microsoft_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignemailbatch',
            name='transport_provider',
            field=models.CharField(choices=[('microsoft_graph', 'Microsoft Graph')], default='microsoft_graph', max_length=24),
        ),
    ]
