# Generated by Django 5.0.4 on 2026-10-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0034_alter_campaignemailbatch_transport_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignemailbatch',
            name='status',
            field=models.CharField(choices=[('queued', 'Chờ gửi'), ('dispatching', 'Đang chuyển'), ('accepted', 'Microsoft Graph đã nhận'), ('processing', 'Đang gửi'), ('completed', 'Hoàn tất'), ('partially_failed', 'Hoàn tất một phần'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy')], db_index=True, default='queued', max_length=24),
        ),
        migrations.AlterField(
            model_name='campaignemaildelivery',
            name='status',
            field=models.CharField(choices=[('queued', 'Chờ gửi'), ('submitting', 'Đang chuyển'), ('accepted', 'Microsoft Graph đã nhận'), ('sent', 'Đã gửi'), ('failed', 'Thất bại'), ('skipped', 'Bỏ qua'), ('cancelled', 'Đã hủy')], db_index=True, default='queued', max_length=16),
        ),
    ]
