# Generated by Django 5.0.4 on 2026-10-08 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0039_update_default_area_confirmation_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_type', models.CharField(choices=[('pgd_response', 'Step 2 · PGD phản hồi lỗi'), ('area_monitoring', 'Step 3 · QLKV theo dõi PGD'), ('area_confirmation', 'Step 5 · QLKV xác nhận lỗi')], db_index=True, max_length=30)),
                ('subject_template', models.CharField(max_length=500)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dec_email_template_master',
                'ordering': ['email_type', 'name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='area_confirmation_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_confirmation_campaigns', to='app_document_campaigns.emailtemplatemaster'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='area_monitoring_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_monitoring_campaigns', to='app_document_campaigns.emailtemplatemaster'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='pgd_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pgd_campaigns', to='app_document_campaigns.emailtemplatemaster'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplatemaster',
            constraint=models.UniqueConstraint(fields=('email_type', 'name'), name='dec_uq_email_template_type_name'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplatemaster',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('email_type',), name='dec_uq_default_email_template_type'),
        ),
    ]
