# Generated by Django 5.0.4 on 2026-10-08 10:42

from django.db import migrations, models


def copy_existing_guidance(apps, schema_editor):
    Campaign = apps.get_model('app_document_campaigns', 'Campaign')
    Campaign.objects.exclude(area_manager_instructions='').update(
        area_monitoring_instructions=models.F('area_manager_instructions'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0041_seed_email_template_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='area_monitoring_instructions',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Hướng dẫn QLKV theo dõi PGD'),
        ),
        migrations.RunPython(copy_existing_guidance, migrations.RunPython.noop),
    ]
