# Generated by Django 5.0.4 on 2026-10-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0042_campaign_area_monitoring_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='carryover_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carryover_campaigns', to='app_document_campaigns.campaign', verbose_name='Nguồn lỗi treo'),
        ),
        migrations.AddField(
            model_name='campaignerror',
            name='carried_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carried_errors', to='app_document_campaigns.campaignerror', verbose_name='Lỗi treo từ kỳ trước'),
        ),
        migrations.AlterField(
            model_name='campaignerror',
            name='status',
            field=models.CharField(choices=[('ready', 'Sẵn sàng phát hành'), ('waiting_shop', 'Chờ PGD phản hồi'), ('shop_draft', 'PGD đang cập nhật'), ('shop_submitted', 'Chờ team kiểm tra'), ('shop_supplement', 'Yêu cầu PGD bổ sung'), ('waiting_area', 'Chờ Area xác nhận'), ('area_returned', 'Area yêu cầu xử lý lại'), ('area_confirmed', 'Area đã xác nhận'), ('closed', 'Đã chốt'), ('excluded', 'Loại khỏi chiến dịch'), ('suspended', 'Treo lỗi sang kỳ sau'), ('cancelled', 'Đã hủy')], default='ready', max_length=30),
        ),
        migrations.AlterField(
            model_name='teamreview',
            name='decision',
            field=models.CharField(choices=[('approved', 'Phê duyệt'), ('supplement', 'Yêu cầu bổ sung'), ('excluded', 'Loại khỏi chiến dịch'), ('suspended', 'Treo lỗi')], max_length=20),
        ),
    ]
