# Generated by Django 5.0.4 on 2026-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_document_campaigns', '0043_campaign_carryover_source_campaignerror_carried_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignemailconfig',
            name='cc_shop_manager',
            field=models.BooleanField(default=False),
        ),
    ]
