# Generated by Django 4.2.7 on 2024-05-20 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingStatus',
            fields=[
                ('borrow_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_status_code', models.CharField(default=None, max_length=3, unique=True)),
                ('borrow_status_name', models.CharField(default=None, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('business_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_type_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('business_type_code', models.CharField(max_length=10, unique=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'd_BusinessType',
            },
        ),
        migrations.CreateModel(
            name='CheckingStatusType',
            fields=[
                ('status_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_type_code', models.IntegerField(unique=True)),
                ('status_type_name', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckingTransactionStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('checking_status_name', models.CharField(default=None, max_length=300, unique=True)),
                ('checking_status_code', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_allowed_to_borrow', models.BooleanField(default=True)),
                ('checking_status_type', models.ForeignKey(db_column='checking_status_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.checkingstatustype')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_CheckingStatus',
            },
        ),
        migrations.CreateModel(
            name='DocumentsDetail',
            fields=[
                ('documents_id', models.AutoField(primary_key=True, serialize=False)),
                ('documents_code', models.CharField(default=None, max_length=50, unique=True)),
                ('documents_created_date', models.DateField()),
                ('lastest_checked_date', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('business_type_id', models.ForeignKey(db_column='business_type_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.businesstype')),
            ],
            options={
                'db_table': 'f_DocumentsDetail',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_code', models.CharField(default=None, max_length=50, unique=True)),
                ('folder_created_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('lastest_received_date', models.DateTimeField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('is_issue', models.BooleanField(null=True)),
                ('row_created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'f_FolderDetail',
            },
        ),
        migrations.CreateModel(
            name='FolderStatus',
            fields=[
                ('folder_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_status_code', models.CharField(default=None, max_length=3, unique=True)),
                ('folder_status_name', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'd_FolderStatus',
            },
        ),
        migrations.CreateModel(
            name='FolderType',
            fields=[
                ('folder_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_type_code', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('folder_type_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('package_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'd_FolderType',
            },
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_code', models.CharField(blank=True, default=None, max_length=11, unique=True)),
                ('customer_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('employee_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('employee_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
            options={
                'db_table': 'd_LoanDetail',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_code', models.CharField(max_length=100, unique=True)),
                ('qlkv_code', models.CharField(max_length=10)),
                ('qlkv_name', models.CharField(default=None, max_length=255)),
                ('qlkv_email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('qlv_code', models.CharField(default=None, max_length=10)),
                ('qlv_name', models.CharField(default=None, max_length=255)),
                ('qlv_email', models.EmailField(blank=True, default=None, max_length=100, null=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'd_Manager',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_code', models.CharField(default=None, max_length=30, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('package_code_old', models.CharField(blank=True, default=None, max_length=30, null=True, unique=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package_type', models.ForeignKey(db_column='package_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.foldertype')),
            ],
            options={
                'db_table': 'd_Package',
            },
        ),
        migrations.CreateModel(
            name='PartnerPackageStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_status_name', models.CharField(default=None, max_length=300, unique=True)),
            ],
            options={
                'db_table': 'd_PartnerPackageStatus',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_code', models.CharField(max_length=10, unique=True)),
                ('region_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'd_Region',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shop_name', models.CharField(max_length=255, unique=True)),
                ('shop_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('is_shop_active', models.BooleanField(default=True)),
                ('shop_closed_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('manager_id', models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.manager')),
                ('region_id', models.ForeignKey(db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.region')),
            ],
            options={
                'db_table': 'd_Shops',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default=None, max_length=100)),
                ('employee_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('region', models.ForeignKey(db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.region')),
                ('shop', models.ForeignKey(db_column='shop_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.shop')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'd_UserProfile',
            },
        ),
        migrations.CreateModel(
            name='TempFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('region_name', models.CharField(max_length=255)),
                ('qlkv_user_code', models.CharField(max_length=255)),
                ('qlkv_name', models.CharField(max_length=255)),
                ('qlv_user_code', models.CharField(max_length=255)),
                ('qlv_name', models.CharField(max_length=255)),
                ('folder_type_code', models.CharField(max_length=255)),
                ('folder_create_date', models.DateField()),
                ('folder_code', models.CharField(max_length=255)),
                ('is_original', models.BooleanField(default=False)),
                ('is_issue', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('error_list', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_code', models.CharField(max_length=255)),
                ('qlkv_name', models.CharField(max_length=255)),
                ('qlv_name', models.CharField(max_length=255)),
                ('qlkv_user_code', models.CharField(max_length=255)),
                ('qlv_user_code', models.CharField(max_length=255)),
                ('document_create_date', models.DateField()),
                ('loan_code', models.CharField(max_length=255, null=True)),
                ('employee_code', models.CharField(max_length=255)),
                ('employee_name', models.CharField(max_length=255)),
                ('customer_code', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('shop_code', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('region_name', models.CharField(max_length=255)),
                ('business_type_name', models.CharField(max_length=255)),
                ('document_type_name', models.CharField(max_length=255)),
                ('folder_type_code', models.CharField(max_length=255)),
                ('folder_code', models.CharField(max_length=255)),
                ('is_original', models.BooleanField(default=False)),
                ('is_issue', models.BooleanField(default=False)),
                ('is_error', models.BooleanField(default=False)),
                ('error_list', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_package_code', models.CharField(default=None, max_length=50, unique=True)),
                ('partner_name', models.CharField(blank=True, default=None, max_length=3, null=True, verbose_name={'CRN': 'Crown'})),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('package_id', models.OneToOneField(db_column='package_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.package')),
                ('status_id', models.ForeignKey(db_column='partnerpackagestatus_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.partnerpackagestatus')),
            ],
            options={
                'db_table': 'd_PartnerPackage',
            },
        ),
        migrations.CreateModel(
            name='PackageFolderHistory',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('folder_id', models.ForeignKey(db_column='folder_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.folder')),
                ('package_id', models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.package')),
                ('trans_created_by', models.ForeignKey(db_column='trans_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folderpackage_created_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_PackageFolderHistory',
            },
        ),
        migrations.CreateModel(
            name='PackageDocumentHistory',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('document_id', models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.documentsdetail')),
                ('package_id', models.ForeignKey(db_column='package_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.package')),
                ('trans_created_by', models.ForeignKey(db_column='trans_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentpackage_created_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_PackageDocumentHistory',
            },
        ),
        migrations.CreateModel(
            name='FoldersTransactionReceiving',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('trans_updated_date', models.DateTimeField(blank=True, null=True)),
                ('folder_id', models.ForeignKey(db_column='folder_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.folder')),
                ('folder_status_id', models.ForeignKey(blank=True, db_column='folder_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.folderstatus')),
                ('trans_created_by', models.ForeignKey(db_column='trans_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_created_transactions', to=settings.AUTH_USER_MODEL)),
                ('trans_updated_by', models.ForeignKey(db_column='trans_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_upated_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_FoldersTransactionReceiving',
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_status_id',
            field=models.ForeignKey(blank=True, db_column='folder_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.folderstatus'),
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_type_id',
            field=models.ForeignKey(db_column='folder_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.foldertype'),
        ),
        migrations.AddField(
            model_name='folder',
            name='lastest_received_by',
            field=models.ForeignKey(blank=True, db_column='lastest_received_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='manager_id',
            field=models.ForeignKey(blank=True, db_column='manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.manager'),
        ),
        migrations.AddField(
            model_name='folder',
            name='package_id',
            field=models.ForeignKey(blank=True, db_column='package_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.package'),
        ),
        migrations.AddField(
            model_name='folder',
            name='shop_id',
            field=models.ForeignKey(db_column='shop_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.shop'),
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('document_type_code', models.CharField(max_length=10, unique=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'd_DocumentType',
            },
        ),
        migrations.CreateModel(
            name='DocumentsTransactionChecking',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_created_date', models.DateTimeField(auto_now_add=True)),
                ('trans_updated_date', models.DateTimeField(blank=True, null=True)),
                ('checking_status_id', models.ForeignKey(db_column='checking_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.checkingtransactionstatus')),
                ('documents_id', models.ForeignKey(db_column='documents_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.documentsdetail')),
                ('trans_created_by', models.ForeignKey(db_column='trans_created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checking_created_transaction', to=settings.AUTH_USER_MODEL)),
                ('trans_updated_by', models.ForeignKey(blank=True, db_column='trans_updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checking_updated_transaction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_DocumentsTransactionChecking',
            },
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('documents_status_name', models.CharField(default=None, max_length=300, unique=True)),
                ('documents_status_code', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'd_DocumentsStatus',
            },
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='document_status_id',
            field=models.ForeignKey(blank=True, db_column='document_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.documentstatus'),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='document_type_id',
            field=models.ForeignKey(db_column='document_type_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.documenttype'),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='folder_id',
            field=models.ForeignKey(blank=True, db_column='folder_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.folder'),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='lastest_checked_by',
            field=models.ForeignKey(blank=True, db_column='lastest_checked_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='loan_id',
            field=models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.loandetail'),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='manager_id',
            field=models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.manager'),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='package_id',
            field=models.ForeignKey(blank=True, db_column='package_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.package'),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='shop_id',
            field=models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.shop'),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='status_id',
            field=models.ForeignKey(blank=True, db_column='check_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.checkingtransactionstatus'),
        ),
        migrations.CreateModel(
            name='CheckingAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('date_addition', models.DateField(blank=True, null=True)),
                ('additional_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('additional_updated_date', models.DateTimeField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('additional', models.OneToOneField(db_column='additional', on_delete=django.db.models.deletion.CASCADE, to='app_documents.documentsdetail')),
                ('additional_created_by', models.ForeignKey(db_column='additional_created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_CheckingAdditional',
            },
        ),
        migrations.AddField(
            model_name='businesstype',
            name='folder_type_id',
            field=models.ForeignKey(db_column='folder_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.foldertype'),
        ),
        migrations.CreateModel(
            name='BorrowingDocument',
            fields=[
                ('borrow_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrow_date', models.DateField()),
                ('appointment_date', models.DateField(null=True)),
                ('return_date', models.DateField()),
                ('ticket_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('borrow_status_id', models.ForeignKey(db_column='borrow_status_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.borrowingstatus')),
                ('borrower', models.ForeignKey(db_column='borrower', on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to=settings.AUTH_USER_MODEL)),
                ('documents_id', models.ForeignKey(db_column='documents_id', on_delete=django.db.models.deletion.CASCADE, to='app_documents.documentsdetail')),
                ('lender', models.ForeignKey(db_column='lender', on_delete=django.db.models.deletion.CASCADE, related_name='lender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_BorrowingDocument',
            },
        ),
    ]
