# Generated by Django 5.0.4 on 2025-11-11 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManager',
            fields=[
                ('areaManager_id', models.AutoField(db_column='area_manager_id', primary_key=True, serialize=False)),
                ('areaManager_code', models.CharField(db_column='area_manager_code', max_length=10, unique=True)),
                ('areaManager_name', models.CharField(db_column='area_manager_name', default=None, max_length=255)),
                ('areaManager_email', models.EmailField(blank=True, db_column='area_manager_email', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'd_AreaManager',
            },
        ),
        migrations.CreateModel(
            name='ContractDetail',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_code', models.CharField(blank=True, default=None, max_length=30, unique=True)),
            ],
            options={
                'db_table': 'd_ContractDetail',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=100, unique=True)),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'd_Employee',
            },
        ),
        migrations.CreateModel(
            name='FolderDeadlineRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('deadline_day', models.IntegerField()),
                ('next_month', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'd_Folder_deadline_rule',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'd_Gender',
            },
        ),
        migrations.CreateModel(
            name='LoanCustomer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_code', models.CharField(blank=True, default=None, max_length=100, unique=True)),
                ('customer_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'd_LoanCustomer',
            },
        ),
        migrations.RemoveField(
            model_name='tempfolder',
            name='user',
        ),
        migrations.AddField(
            model_name='borrowingdocument',
            name='borrower_detail',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrowingstatus',
            name='badge_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowingstatus',
            name='flag_is_borrowing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowingstatus',
            name='flag_is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowingstatus',
            name='flag_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='action_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='allow_checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesstype',
            name='need_action_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='is_pending_metadata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='badge_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='is_borrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentstatus',
            name='is_selectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_late',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_on_time',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_out_of_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='folderstatus',
            name='badge_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='folderstatus',
            name='is_borrow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderstatus',
            name='is_lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderstatus',
            name='is_not_received_yet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderstatus',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderstatus',
            name='is_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='region_id',
            field=models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.region'),
        ),
        migrations.AddField(
            model_name='partnerpackagestatus',
            name='badge_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partnerpackagestatus',
            name='is_backed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerpackagestatus',
            name='is_in_warehouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerpackagestatus',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='for_borrow_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowingdocument',
            name='borrower',
            field=models.ForeignKey(db_column='borrower', on_delete=django.db.models.deletion.CASCADE, related_name='borrower', to='app_documents.shop'),
        ),
        migrations.AlterField(
            model_name='borrowingdocument',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='business_type_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='business_type_name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentsdetail',
            name='business_type_id',
            field=models.ForeignKey(db_column='business_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.businesstype'),
        ),
        migrations.AlterField(
            model_name='documentsdetail',
            name='document_type_id',
            field=models.ForeignKey(db_column='document_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.documenttype'),
        ),
        migrations.AlterField(
            model_name='documentsdetail',
            name='loan_id',
            field=models.ForeignKey(db_column='loan_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.loandetail'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='customer_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='employee_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='employee_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loandetail',
            name='loan_code',
            field=models.CharField(blank=True, default=None, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='partnerpackage',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='borrowingstatus',
            table='d_BorrowingStatus',
        ),
        migrations.AlterModelTable(
            name='checkingstatustype',
            table='d_CheckingStatusType',
        ),
        migrations.AddField(
            model_name='manager',
            name='areaManager',
            field=models.ForeignKey(blank=True, db_column='area_manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_manager', to='app_documents.areamanager'),
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('request_type', models.CharField(choices=[('folder', 'Folder'), ('document', 'Document')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.documentsdetail')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_Change_request',
            },
        ),
        migrations.AddField(
            model_name='documentsdetail',
            name='contract_id',
            field=models.ForeignKey(db_column='contract_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.contractdetail'),
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.employee'),
        ),
        migrations.AddField(
            model_name='loandetail',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.employee'),
        ),
        migrations.CreateModel(
            name='FolderGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day_from', models.IntegerField(blank=True, null=True)),
                ('day_to', models.IntegerField(blank=True, null=True)),
                ('rule_deadline', models.ForeignKey(db_column='rule_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.folderdeadlinerule')),
            ],
            options={
                'db_table': 'd_Folder_group',
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='group',
            field=models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.foldergroup'),
        ),
        migrations.AddField(
            model_name='areamanager',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.gender'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.gender'),
        ),
        migrations.CreateModel(
            name='HistoricalDocuments',
            fields=[
                ('documents_id', models.AutoField(primary_key=True, serialize=False)),
                ('documents_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('business_type', models.CharField(blank=True, db_column='business_type_name', max_length=500, null=True)),
                ('document_type', models.TextField(blank=True, db_column='document_type_name', null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('condition', models.TextField(blank=True, null=True)),
                ('is_original', models.BooleanField(default=True)),
                ('is_issue', models.BooleanField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_column='loan_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.loandetail')),
                ('package', models.ForeignKey(blank=True, db_column='package_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.package')),
                ('region', models.ForeignKey(db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.region')),
                ('shop', models.ForeignKey(blank=True, db_column='shop_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.shop')),
            ],
            options={
                'db_table': 'historical_documents',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFolder',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('folder_created_date', models.DateField()),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('is_original', models.BooleanField(default=True)),
                ('is_issue', models.BooleanField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder_status', models.ForeignKey(blank=True, db_column='folder_status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.folderstatus')),
                ('folder_type', models.ForeignKey(blank=True, db_column='folder_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.foldertype')),
                ('package', models.ForeignKey(blank=True, db_column='package_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.package')),
                ('region', models.ForeignKey(db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_documents.region')),
                ('shop', models.ForeignKey(blank=True, db_column='shop_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.shop')),
            ],
            options={
                'db_table': 'historical_folder',
            },
        ),
        migrations.AddField(
            model_name='contractdetail',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.loancustomer'),
        ),
        migrations.AddField(
            model_name='loandetail',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.loancustomer'),
        ),
        migrations.CreateModel(
            name='RegionManager',
            fields=[
                ('regionManager_id', models.AutoField(db_column='region_manager_id', primary_key=True, serialize=False)),
                ('regionManager_code', models.CharField(db_column='region_manager_code', max_length=10, unique=True)),
                ('regionManager_name', models.CharField(db_column='region_manager_name', default=None, max_length=255)),
                ('regionManager_email', models.EmailField(blank=True, db_column='region_manager_email', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_documents.gender')),
            ],
            options={
                'db_table': 'd_RegionManager',
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='regionManager',
            field=models.ForeignKey(blank=True, db_column='region_manager_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_manager', to='app_documents.regionmanager'),
        ),
        migrations.DeleteModel(
            name='TempDocument',
        ),
        migrations.DeleteModel(
            name='TempFolder',
        ),
    ]
