# Generated by Django 5.0.4 on 2025-11-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0003_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='require_partner_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='require_partner_selection',
            field=models.BooleanField(default=True),
        ),
    ]
