# Generated by Django 5.0.4 on 2025-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0004_partner_require_partner_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpackage',
            name='partner_name',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='partnerpackage',
            name='partner_package_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
