# Generated by Django 5.0.4 on 2025-11-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0005_alter_partnerpackage_partner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gapo_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
