# Generated by Django 5.0.4 on 2025-11-27 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0006_userprofile_gapo_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GapoScheduledMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('schedule_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gapo_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'f_GapoScheduledMessage',
                'ordering': ['-created_at'],
            },
        ),
    ]
