# Generated by Codex on 2026-01-13
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0010_package_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentKpiSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=60, unique=True)),
                ('metric_name', models.CharField(max_length=255)),
                ('target_rate', models.DecimalField(decimal_places=2, default=90.0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ],
            options={
                'db_table': 'd_DocumentKpiSetting',
            },
        ),
    ]
