# Generated by Django 5.0.4 on 2025-11-20 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmAdministrativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_number', models.PositiveIntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=500)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='admindocuments/files/%Y/%m/')),
                ('ticket_code', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('document_number_full', models.CharField(editable=False, max_length=255, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_document_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_document_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrative Document',
                'verbose_name_plural': 'Administrative Documents',
                'db_table': 'adm_administrative_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmAdministrativeDocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app_admindocuments.admadministrativedocument')),
            ],
            options={
                'verbose_name': 'Administrative Document History',
                'verbose_name_plural': 'Administrative Document Histories',
                'db_table': 'adm_administrative_document_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_company_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_company_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'adm_company',
            },
        ),
        migrations.AddField(
            model_name='admadministrativedocument',
            name='issuing_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admindocuments.admcompany'),
        ),
        migrations.CreateModel(
            name='AdmContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_contenttype_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_contenttype_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
                'db_table': 'adm_content_type',
            },
        ),
        migrations.AddField(
            model_name='admadministrativedocument',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admindocuments.admcontenttype'),
        ),
        migrations.CreateModel(
            name='AdmDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app_admindocuments.admcompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_department_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_department_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'adm_department',
            },
        ),
        migrations.AddField(
            model_name='admadministrativedocument',
            name='issuing_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admindocuments.admdepartment'),
        ),
        migrations.CreateModel(
            name='AdmDocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_documentstatus_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_documentstatus_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Status',
                'verbose_name_plural': 'Document Statuses',
                'db_table': 'adm_document_status',
            },
        ),
        migrations.AddField(
            model_name='admadministrativedocument',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admindocuments.admdocumentstatus'),
        ),
        migrations.CreateModel(
            name='AdmDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_documenttype_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_documenttype_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'db_table': 'adm_document_type',
            },
        ),
        migrations.AddField(
            model_name='admadministrativedocument',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admindocuments.admdocumenttype'),
        ),
        migrations.CreateModel(
            name='AdmPaperDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=50)),
                ('running_number', models.PositiveIntegerField()),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('responsible_person', models.CharField(max_length=255)),
                ('ticket_code', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(max_length=500)),
                ('courier_company', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_tracking_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_paperdoc_created_by', to=settings.AUTH_USER_MODEL)),
                ('requested_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admindocuments.admdepartment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_paperdoc_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paper Document',
                'verbose_name_plural': 'Paper Documents',
                'db_table': 'adm_paper_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmSignerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_signerrole_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_signerrole_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signer Role',
                'verbose_name_plural': 'Signer Roles',
                'db_table': 'adm_signer_role',
            },
        ),
        migrations.AddField(
            model_name='admadministrativedocument',
            name='signer_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admindocuments.admsignerrole'),
        ),
        migrations.CreateModel(
            name='AdmDocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admindocuments.admdocumenttype')),
            ],
            options={
                'verbose_name': 'Document Counter',
                'verbose_name_plural': 'Document Counters',
                'db_table': 'adm_document_counter',
                'unique_together': {('doc_type', 'year')},
            },
        ),
    ]
