# Generated by Django 5.0.4 on 2025-11-20 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0001_initial'),
        ('app_documents', '0005_alter_partnerpackage_partner_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmCourierCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Company',
                'verbose_name_plural': 'Courier Companies',
                'db_table': 'adm_courier_company',
            },
        ),
        migrations.CreateModel(
            name='AdmPaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paper Type',
                'verbose_name_plural': 'Paper Types',
                'db_table': 'adm_paper_type',
            },
        ),
        migrations.AddField(
            model_name='admpaperdocument',
            name='document_number_full',
            field=models.CharField(default=123, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admpaperdocument',
            name='requested_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_documents.shop'),
        ),
        migrations.AlterField(
            model_name='admpaperdocument',
            name='courier_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admindocuments.admcouriercompany'),
        ),
        migrations.AlterField(
            model_name='admpaperdocument',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admindocuments.admpapertype'),
        ),
    ]
