# Generated by Django 5.0.4 on 2025-12-03 21:54

import app_admindocuments.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0002_admcouriercompany_admpapertype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admdocumentcounter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='admdocumentcounter',
            name='company',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_admindocuments.admcompany'),
        ),
        migrations.AlterUniqueTogether(
            name='admdocumentcounter',
            unique_together={('doc_type', 'company', 'year')},
        ),
        migrations.CreateModel(
            name='AdmDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=app_admindocuments.models._attachment_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_doc_attachment_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_doc_attachment_deleted', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app_admindocuments.admadministrativedocument')),
            ],
            options={
                'db_table': 'adm_document_attachment',
                'ordering': ['-version'],
                'unique_together': {('document', 'version')},
            },
        ),
    ]
