# Generated by Django 5.0.4 on 2025-12-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0004_administrativedocument_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admdocumentcounter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admindocuments.admcompany'),
        ),
    ]
