# Generated by Django on 2026-02-22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0012_add_company_badge_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admpapercounter',
            options={'verbose_name': 'Paper Counter', 'verbose_name_plural': 'Paper Counters'},
        ),
        migrations.AlterField(
            model_name='admpapercounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AdmIncomingDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=255, unique=True)),
                ('sending_unit', models.CharField(max_length=255)),
                ('received_date', models.DateField(db_index=True, default=datetime.date.today, editable=False)),
                ('signer_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('receiving_company', models.ForeignKey(db_column='receiving_company', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_dispatches_received', to='app_admindocuments.admcompany', to_field='code')),
                ('status', models.CharField(choices=[('to_btl', 'Chuyển BTL xử lý'), ('to_pc', 'Chuyển PC xử lý'), ('in_progress', 'Đang xử lý'), ('done', 'Hoàn tất'), ('archived', 'Lưu trữ')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_incoming_dispatch_created_by', to=settings.AUTH_USER_MODEL)),
                ('processing_departments', models.ManyToManyField(related_name='incoming_dispatches', to='app_admindocuments.admdepartment')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adm_incoming_dispatch_responsible', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_incoming_dispatch_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Dispatch',
                'verbose_name_plural': 'Incoming Dispatches',
                'db_table': 'adm_incoming_dispatch',
                'ordering': ['-created_at'],
            },
        ),
    ]
