# Generated by Django 5.0.4 on 2026-02-22 13:25

import django.db.models.deletion
from django.db import migrations, models


def seed_incoming_dispatch_catalogs(apps, schema_editor):
    status_model = apps.get_model("app_admindocuments", "AdmIncomingDispatchStatus")
    type_model = apps.get_model("app_admindocuments", "AdmIncomingDispatchType")

    statuses = [
        ("to_btl", "Chuyển BTL xử lý", 1),
        ("to_pc", "Chuyển PC xử lý", 2),
        ("in_progress", "Đang xử lý", 3),
        ("done", "Hoàn tất", 4),
        ("archived", "Lưu trữ", 5),
    ]
    for code, name, order in statuses:
        status_model.objects.update_or_create(
            code=code,
            defaults={"name": name, "sort_order": order, "is_active": True},
        )

    types = [
        ("cong_van", "Công văn", 1),
        ("buu_pham", "Bưu phẩm", 2),
        ("buu_kien", "Bưu kiện", 3),
    ]
    for code, name, order in types:
        type_model.objects.update_or_create(
            code=code,
            defaults={"name": name, "sort_order": order, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0013_alter_admpapercounter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmIncomingDispatchStatus',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Incoming Dispatch Status',
                'verbose_name_plural': 'Incoming Dispatch Statuses',
                'db_table': 'adm_incoming_dispatch_status',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmIncomingDispatchType',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Incoming Dispatch Type',
                'verbose_name_plural': 'Incoming Dispatch Types',
                'db_table': 'adm_incoming_dispatch_type',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdmIncomingGapoGroup',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gapo_group_id', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Incoming Gapo Group',
                'verbose_name_plural': 'Incoming Gapo Groups',
                'db_table': 'adm_incoming_gapo_group',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(seed_incoming_dispatch_catalogs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='admincomingdispatch',
            name='status',
            field=models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_dispatches', to='app_admindocuments.admincomingdispatchstatus'),
        ),
        migrations.AddField(
            model_name='admincomingdispatch',
            name='incoming_item_type',
            field=models.ForeignKey(blank=True, db_column='incoming_item_type', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_dispatches', to='app_admindocuments.admincomingdispatchtype'),
        ),
        migrations.AddField(
            model_name='admincomingdispatch',
            name='gapo_group',
            field=models.ForeignKey(blank=True, db_column='gapo_group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_dispatches', to='app_admindocuments.admincominggapogroup'),
        ),
    ]
