# Generated by Django 5.0.4 on 2026-02-25 09:35

from django.db import migrations


def normalize_incoming_dispatch_types(apps, schema_editor):
    DispatchType = apps.get_model("app_admindocuments", "AdmIncomingDispatchType")

    DispatchType.objects.update_or_create(
        code="cong_van",
        defaults={"name": "Công văn đến", "sort_order": 1, "is_active": True},
    )
    DispatchType.objects.update_or_create(
        code="buu_pham_buu_kien",
        defaults={"name": "Bưu phẩm/bưu kiện", "sort_order": 2, "is_active": True},
    )
    DispatchType.objects.filter(code__in=["buu_pham", "buu_kien"]).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0014_admincomingdispatchstatus_admincomingdispatchtype_and_more'),
    ]

    operations = [
        migrations.RunPython(
            normalize_incoming_dispatch_types,
            migrations.RunPython.noop,
        ),
    ]
