# Generated by Django 5.0.4 on 2026-02-25 14:51

import app_admindocuments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_incoming_workflow_statuses(apps, schema_editor):
    Status = apps.get_model("app_admindocuments", "AdmIncomingDispatchStatus")
    statuses = [
        ("doc_received", "Đã tiếp nhận", 1),
        ("doc_at_clerical", "Đang ở Văn thư", 2),
        ("doc_at_assistant", "Đang ở Ban trợ lý", 3),
        ("doc_pending_signer", "Trình ký", 4),
        ("doc_archived", "Lưu trữ", 5),
        ("pkg_received", "Đã tiếp nhận", 6),
        ("pkg_at_clerical", "Đang ở Văn thư", 7),
        ("pkg_processing", "Đang xử lý", 8),
        ("pkg_archived", "Lưu trữ", 9),
    ]
    for code, name, sort_order in statuses:
        Status.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0015_admsignerrole_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincomingdispatch',
            name='document_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='AdmIncomingDispatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=app_admindocuments.models._incoming_dispatch_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_admindocuments.admincomingdispatch')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_incoming_dispatch_images_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Dispatch Image',
                'verbose_name_plural': 'Incoming Dispatch Images',
                'db_table': 'adm_incoming_dispatch_image',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RunPython(seed_incoming_workflow_statuses, migrations.RunPython.noop),
    ]
