# Generated by Django 5.0.4 on 2026-03-20 16:27

import app_admindocuments.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def split_parcel_receipts_from_incoming_dispatch(apps, schema_editor):
    IncomingDispatch = apps.get_model("app_admindocuments", "AdmIncomingDispatch")
    IncomingDispatchImage = apps.get_model("app_admindocuments", "AdmIncomingDispatchImage")
    ParcelReceipt = apps.get_model("app_admindocuments", "AdmParcelReceipt")
    ParcelReceiptImage = apps.get_model("app_admindocuments", "AdmParcelReceiptImage")

    parcel_ids = []
    id_map = {}

    for dispatch in IncomingDispatch.objects.filter(
        incoming_item_type_id="buu_pham_buu_kien"
    ).order_by("id"):
        parcel_receipt = ParcelReceipt.objects.create(
            document_number=dispatch.document_number,
            responsible_user_id=dispatch.responsible_user_id,
            sending_unit=dispatch.sending_unit,
            received_date=dispatch.received_date,
            signer_name=dispatch.signer_name,
            summary=dispatch.summary,
            receiving_company_id=dispatch.receiving_company_id,
            status_id=dispatch.status_id,
            gapo_group_id=dispatch.gapo_group_id,
            created_by_id=dispatch.created_by_id,
            updated_by_id=dispatch.updated_by_id,
            created_at=dispatch.created_at,
            updated_at=dispatch.updated_at,
        )
        parcel_receipt.processing_departments.set(
            dispatch.processing_departments.values_list("id", flat=True)
        )
        parcel_ids.append(dispatch.id)
        id_map[dispatch.id] = parcel_receipt.id

    if not id_map:
        return

    for image in IncomingDispatchImage.objects.filter(dispatch_id__in=parcel_ids):
        image_name = getattr(image.image, "name", image.image)
        ParcelReceiptImage.objects.create(
            parcel_receipt_id=id_map[image.dispatch_id],
            image=image_name,
            uploaded_at=image.uploaded_at,
            uploaded_by_id=image.uploaded_by_id,
        )

    IncomingDispatch.objects.filter(id__in=parcel_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0017_update_parcel_status_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmParcelReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sending_unit', models.CharField(max_length=255)),
                ('received_date', models.DateField(db_index=True, default=datetime.date.today, editable=False)),
                ('signer_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_parcel_receipt_created_by', to=settings.AUTH_USER_MODEL)),
                ('gapo_group', models.ForeignKey(blank=True, db_column='gapo_group', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcel_receipts', to='app_admindocuments.admincominggapogroup')),
                ('processing_departments', models.ManyToManyField(related_name='parcel_receipts', to='app_admindocuments.admdepartment')),
                ('receiving_company', models.ForeignKey(db_column='receiving_company', on_delete=django.db.models.deletion.PROTECT, related_name='parcel_receipts_received', to='app_admindocuments.admcompany', to_field='code')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adm_parcel_receipt_responsible', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, related_name='parcel_receipts', to='app_admindocuments.admincomingdispatchstatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_parcel_receipt_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Receipt',
                'verbose_name_plural': 'Parcel Receipts',
                'db_table': 'adm_parcel_receipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmParcelReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=app_admindocuments.models._parcel_receipt_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parcel_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_admindocuments.admparcelreceipt')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_parcel_receipt_images_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Receipt Image',
                'verbose_name_plural': 'Parcel Receipt Images',
                'db_table': 'adm_parcel_receipt_image',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RunPython(
            split_parcel_receipts_from_incoming_dispatch,
            migrations.RunPython.noop,
        ),
    ]
