# Generated by Django 5.0.4 on 2026-03-24 10:30

import app_admindocuments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0019_admparcelsendersuggestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmParcelRecipientCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('gapo_user_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('employee_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('full_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('employment_status', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('permission_name', models.CharField(blank=True, default='', max_length=100)),
                ('org_chart', models.CharField(blank=True, default='', max_length=255)),
                ('position_name', models.CharField(blank=True, default='', max_length=255)),
                ('department_full', models.CharField(blank=True, default='', max_length=1000)),
                ('department_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('region_name', models.CharField(blank=True, default='', max_length=255)),
                ('company_join_date', models.CharField(blank=True, default='', max_length=50)),
                ('contract_start_date', models.CharField(blank=True, default='', max_length=50)),
                ('leave_date', models.CharField(blank=True, default='', max_length=50)),
                ('source_created_at', models.CharField(blank=True, default='', max_length=50)),
                ('is_active_member', models.BooleanField(db_index=True, default=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parcel Recipient Catalog',
                'verbose_name_plural': 'Parcel Recipient Catalog',
                'db_table': 'adm_parcel_recipient_catalog',
                'ordering': ['department_name', 'full_name', 'employee_code'],
            },
        ),
        migrations.AddField(
            model_name='admparcelreceipt',
            name='recipient_employee_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admparcelreceipt',
            name='recipient_gapo_user_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admparcelreceipt',
            name='recipient_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='admparcelreceipt',
            name='recipient_directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcel_receipts', to='app_admindocuments.admparcelrecipientcatalog'),
        ),
        migrations.CreateModel(
            name='AdmParcelRecipientImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=app_admindocuments.models._parcel_recipient_import_upload_path)),
                ('sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('active_rows', models.PositiveIntegerField(default=0)),
                ('has_errors', models.BooleanField(default=False)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_parcel_recipient_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Recipient Import Batch',
                'verbose_name_plural': 'Parcel Recipient Import Batches',
                'db_table': 'adm_parcel_recipient_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='admparcelrecipientcatalog',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='app_admindocuments.admparcelrecipientimportbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='admparcelrecipientcatalog',
            unique_together={('import_batch', 'row_number')},
        ),
    ]
