# Generated by Django 5.0.4 on 2026-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0020_admparcelrecipientcatalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admparcelrecipientcatalog',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admparcelrecipientcatalog',
            name='phone_number_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
    ]
