# Generated by Django 5.0.4 on 2026-03-26 14:59

import app_admindocuments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0021_admparcelrecipientcatalog_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admparcelreceipt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admparcelreceiptlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('notified', 'Notified'), ('confirmed', 'Confirmed'), ('handed_over', 'Handed Over'), ('proxy_registered', 'Proxy Registered'), ('updated', 'Updated')], max_length=30),
        ),
        migrations.CreateModel(
            name='AdmParcelNotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=app_admindocuments.models._parcel_token, editable=False, max_length=64, unique=True)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_employee_code', models.CharField(blank=True, default='', max_length=50)),
                ('recipient_gapo_user_id', models.CharField(blank=True, default='', max_length=100)),
                ('recipient_department', models.CharField(blank=True, default='', max_length=255)),
                ('parcel_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('confirmed', 'Confirmed')], default='created', max_length=20)),
                ('message_text', models.TextField(blank=True, default='')),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_receiver_name', models.CharField(blank=True, default='', max_length=255)),
                ('actual_receiver_employee_code', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_parcel_notification_batches_created', to=settings.AUTH_USER_MODEL)),
                ('parcels', models.ManyToManyField(blank=True, related_name='notification_batches', to='app_admindocuments.admparcelreceipt')),
                ('recipient_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_batches', to='app_admindocuments.admparcelrecipientcatalog')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_parcel_notification_batches_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Notification Batch',
                'verbose_name_plural': 'Parcel Notification Batches',
                'db_table': 'adm_parcel_notification_batch',
                'ordering': ['-created_at'],
            },
        ),
    ]
