# Generated by Django 5.0.4 on 2026-03-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0023_update_parcel_status_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='admparcelreceipt',
            name='proxy_receiver_employee_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
