# Generated by Django 5.0.4 on 2026-03-27 10:52

from django.db import migrations, models


def seed_default_parcel_dynamic_template(apps, schema_editor):
    Template = apps.get_model("app_admindocuments", "AdmParcelDynamicTemplate")
    Template.objects.update_or_create(
        template_type="parcel_notify_confirm",
        defaults={
            "name": "Thông báo nhận bưu kiện",
            "title_template": "Bưu kiện đang chờ bạn nhận",
            "body_template": (
                "Hiện có {{parcel_count}} kiện từ {{primary_sender}}. "
                "Liên hệ lễ tân để nhận và bấm nút bên dưới để xác nhận."
            ),
            "button_text": "Bấm vào đây để xác nhận bưu kiện",
            "hero_image_url": "",
            "button_bg_color": "#16A34A",
            "button_text_color": "#FFFFFF",
            "card_border_color": "#DADDE1",
            "is_active": True,
        },
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0024_admparcelreceipt_proxy_receiver_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmParcelDynamicTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('parcel_notify_confirm', 'Thông báo nhận bưu kiện')], default='parcel_notify_confirm', max_length=50, unique=True)),
                ('name', models.CharField(default='Thông báo nhận bưu kiện', max_length=255)),
                ('title_template', models.CharField(default='Bưu kiện đang chờ bạn nhận', max_length=255)),
                ('body_template', models.TextField(default='Hiện có {{parcel_count}} kiện từ {{primary_sender}}. Liên hệ lễ tân để nhận và bấm nút bên dưới để xác nhận.')),
                ('button_text', models.CharField(default='Bấm vào đây để xác nhận bưu kiện', max_length=255)),
                ('hero_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('button_bg_color', models.CharField(default='#16A34A', max_length=20)),
                ('button_text_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('card_border_color', models.CharField(default='#DADDE1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parcel Dynamic Template',
                'verbose_name_plural': 'Parcel Dynamic Templates',
                'db_table': 'adm_parcel_dynamic_template',
                'ordering': ['template_type', '-updated_at'],
            },
        ),
        migrations.RunPython(seed_default_parcel_dynamic_template, noop_reverse),
    ]
