# Generated by Django 5.0.4 on 2026-03-27 14:01

import app_admindocuments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_auto_notify_setting(apps, schema_editor):
    Setting = apps.get_model("app_admindocuments", "AdmParcelAutoNotifySetting")
    Setting.objects.update_or_create(
        code="default",
        defaults={
            "name": "Nhắc lại bưu kiện",
            "skip_weekends": True,
            "is_active": True,
        },
    )


def reset_legacy_parcel_operational_data(apps, schema_editor):
    ParcelReceipt = apps.get_model("app_admindocuments", "AdmParcelReceipt")
    ParcelReceiptImage = apps.get_model("app_admindocuments", "AdmParcelReceiptImage")
    ParcelReceiptLog = apps.get_model("app_admindocuments", "AdmParcelReceiptLog")
    ParcelNotificationBatch = apps.get_model("app_admindocuments", "AdmParcelNotificationBatch")
    GapoScheduledMessage = apps.get_model("app_documents", "GapoScheduledMessage")

    schedule_ids = set(
        ParcelReceipt.objects.exclude(notification_schedule_id__isnull=True).values_list(
            "notification_schedule_id", flat=True
        )
    )
    schedule_ids.update(
        ParcelReceipt.objects.exclude(reminder_schedule_id__isnull=True).values_list(
            "reminder_schedule_id", flat=True
        )
    )
    schedule_ids.update(
        ParcelNotificationBatch.objects.exclude(reminder_schedule_id__isnull=True).values_list(
            "reminder_schedule_id", flat=True
        )
    )

    ParcelReceiptImage.objects.all().delete()
    ParcelReceiptLog.objects.all().delete()
    ParcelNotificationBatch.objects.all().delete()
    ParcelReceipt.objects.all().delete()
    if schedule_ids:
        GapoScheduledMessage.objects.filter(id__in=schedule_ids).delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('app_admindocuments', '0025_admparceldynamictemplate'),
        ('app_documents', '0020_gaposcheduledmessage_body_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admparcelnotificationbatch',
            name='notification_send_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admparcelnotificationbatch',
            name='reminder_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_parcel_notification_batch_reminder_schedule', to='app_documents.gaposcheduledmessage'),
        ),
        migrations.AddField(
            model_name='admparcelnotificationbatch',
            name='reminder_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdmParcelAutoNotifySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='default', max_length=50, unique=True)),
                ('name', models.CharField(default='Nhắc lại bưu kiện', max_length=255)),
                ('reminder_send_time', models.TimeField(default=app_admindocuments.models._parcel_default_reminder_time)),
                ('skip_weekends', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_parcel_auto_notify_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Auto Notify Setting',
                'verbose_name_plural': 'Parcel Auto Notify Settings',
                'db_table': 'adm_parcel_auto_notify_setting',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_auto_notify_setting, noop_reverse),
        migrations.RunPython(reset_legacy_parcel_operational_data, noop_reverse),
    ]
