# Generated by Django 5.0.4 on 2026-03-27 21:23

from django.db import migrations, models


def backfill_reminder_send_times(apps, schema_editor):
    Setting = apps.get_model("app_admindocuments", "AdmParcelAutoNotifySetting")
    for setting in Setting.objects.all():
        current_value = (getattr(setting, "reminder_send_times", "") or "").strip()
        if current_value:
            continue
        reminder_time = getattr(setting, "reminder_send_time", None)
        if reminder_time:
            setting.reminder_send_times = reminder_time.strftime("%H:%M")
            setting.save(update_fields=["reminder_send_times"])


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0026_admparcelnotificationbatch_notification_send_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admparcelautonotifysetting',
            name='reminder_send_times',
            field=models.CharField(default='09:00', help_text='Nhập nhiều khung giờ, phân tách bằng dấu phẩy. Ví dụ: 09:00, 14:00, 16:30', max_length=255),
        ),
        migrations.RunPython(backfill_reminder_send_times, migrations.RunPython.noop),
    ]
