# Generated by Django 5.0.4 on 2026-03-31 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admindocuments', '0029_seed_incoming_document_status_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmIncomingDispatchStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adm_incoming_dispatch_status_logs', to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='app_admindocuments.admincomingdispatch')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_dispatch_logs_from_status', to='app_admindocuments.admincomingdispatchstatus')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_dispatch_logs_to_status', to='app_admindocuments.admincomingdispatchstatus')),
            ],
            options={
                'verbose_name': 'Incoming Dispatch Status Log',
                'verbose_name_plural': 'Incoming Dispatch Status Logs',
                'db_table': 'adm_incoming_dispatch_status_log',
                'ordering': ['-changed_at', '-id'],
            },
        ),
    ]
